version: "3.7"

services:
  imap2jira:
    build:
      context: "."
      dockerfile: Dockerfile
    container_name: imap2jira
    restart: always
    env_file:
      - .env
    volumes:
      - ./service:/go/src/app
      - ./structure_new_issue.json:/go/src/app/structure_new_issue.json
      - ./structure_add_comment.json:/go/src/app/structure_add_comment.json