name: Build docker image

on:
  release:
    types: [published]

jobs:
  build:
    if: "!github.event.release.prerelease"
    runs-on: ubuntu-latest
    steps:
      - name: login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: svenlie
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: actions/checkout@v3
      - name: Build the imap2jira docker image
        run: docker build . --file ./Dockerfile --tag svenlie/imap2jira:${GITHUB_REF##*/} --tag svenlie/imap2jira:latest
      - name: Push imap2jira docker images
        run: docker push svenlie/imap2jira --all-tags
  build-dev:
    if: "github.event.release.prerelease"
    runs-on: ubuntu-latest
    steps:
      - name: login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          username: svenlie
          password: ${{ secrets.DOCKER_TOKEN }}
      - uses: actions/checkout@v3
      - name: Build the imap2jira docker image
        run: docker build . --file ./Dockerfile --tag svenlie/imap2jira:${GITHUB_REF##*/} --tag svenlie/imap2jira:latest-dev
      - name: Push imap2jira docker images
        run: docker push svenlie/imap2jira --all-tags
