name: Build docker image

on:
  release:
    types: [published]

jobs:
  build:
    if: "!github.event.release.prerelease"
    runs-on: ubuntu-latest
    steps:
      - name: login to Docker Hub Registry
        uses: docker/login-action@v2
        with:
          username: svenlie
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          tags: |
              svenlie/imap2jira:latest
              svenlie/imap2jira:${{ steps.vars.outputs.tag }}
              ghcr.io/svenlie/imap2jira:latest
              ghcr.io/svenlie/imap2jira:${{ steps.vars.outputs.tag }}
  build-dev:
    if: "github.event.release.prerelease"
    runs-on: ubuntu-latest
    steps:
      - name: login to Docker Hub Registry
        uses: docker/login-action@v2
        with:
          username: svenlie
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          tags: |
            svenlie/imap2jira:latest-dev
            svenlie/imap2jira:${{ steps.vars.outputs.tag }}
            ghcr.io/svenlie/imap2jira:latest-dev
            ghcr.io/svenlie/imap2jira:${{ steps.vars.outputs.tag }}
